### ISSUE TITLE
OPGG Multisearch Region

### ISSUE THREAD

**Issue by kusuoh** [steele123/reveal#1]
Hi, 

is there a way to change the multisearch from SG2 (Singapore) to just SG?

It shows this page when its on SG2
![image](https://github.com/steele123/reveal/assets/82033411/f3c84fcf-7bbd-4fe4-a518-8caa6c828026)

**Comment by steele123** [comment]
Oh thats odd so in the multilink it is SG2 and not just SG? for ex.
https://www.op.gg/summoners/sg/eat%20shyt%20losers-FF15
is 
https://www.op.gg/summoners/sg2/eat%20shyt%20losers-FF15

if so I suppose I could do some hardcoding for broken regions as these regions are obtained by riots "web region"

**Comment by steele123** [comment]
> https://www.op.gg/multisearch/sg?summoners=Isaac%23CTB%2Cflash2468%23SG2%2COrnnyFans%239963%2Csnowwy%235752
> 
> https://www.op.gg/multisearch/sg? is the correct one instead of https://www.op.gg/multisearch/sg2?
> 
> It only affects the multisearch not profile link

Gotcha, I'll fix this tomorrow!

**Comment by steele123** [comment]
Not publishing release until probably Friday (won't auto update til then), but I'll be putting it in the releases tab for manual download (v1.2.5). Let me know if it all works as expected :)
