### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Icup2476** [steele123/reveal#5]
I'm sure to most it may be obvious, but I am curious how it is that I use this tool. I have downloaded it and looked through a few of the files but don't see an exe. I am stumpt in how to use it. Is it something I need to import into the current game files? If so would you kindly take the time and explain how I can use it or how I launch the tool to be exact. I appreciate and apologize for my naiveness in the matter. Thank you

**Comment by steele123** [comment]
Download from https://hyeb.gg/reveal
